#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

SEARCH  += $(DATASTRUCTURES)/code/headers

# header files in this library
HEADERS += $(wildcard $(DATASTRUCTURES)/code/headers/*.hpp)
